importâ€‹Â â€‹telebot 
 â€‹importâ€‹Â â€‹datetime 
 â€‹importâ€‹Â â€‹time 
  
 â€‹###Â HELPÂ TEXTÂ ------------------------------------------------------------------------| 
 â€‹''' 
 â€‹UserÂ AvailableÂ Commands: 
 â€‹Â Â Â Â 1.Â /poll 
 â€‹Â Â Â Â 2.Â /stats 
 â€‹Â Â Â Â 3.Â /start 
 â€‹Â Â Â Â 4.Â /help 
 â€‹Â Â Â Â 5.Â /groups 
 â€‹Â Â Â  
 â€‹DeveloperÂ Commands:Â #NOTE:Â ON @armiy_vÂ areÂ allowedÂ forÂ theseÂ comands: 
 â€‹Â Â Â Â 1.Â /showIds 
 â€‹Â Â Â Â 2.Â /botlogs 
 â€‹''' 
 â€‹###Â MAINÂ VARSÂ ------------------------------------------------------------------------| 
 â€‹''' 
 â€‹THESEÂ AREÂ THEÂ IMPORTANTÂ VARSÂ FORÂ POLLÂ BOT 
 â€‹''' 
 â€‹BOT_TOKENâ€‹Â â€‹=â€‹Â â€‹'2096017938:AAHOLu9etv-0ZTYQrqmgH-vogXIh7bLqs1w'â€‹Â â€‹#Â YOURÂ BOTÂ TOKENÂ HEREÂ GETÂ FROMÂ @BotFather 
 â€‹API_HASHâ€‹Â â€‹=â€‹Â â€‹'e5f0dd414ea37eee03bc96e4598eaf58'â€‹Â â€‹#Â YOURÂ APIÂ HASHÂ GETÂ FROMÂ my.telegram.org 
 â€‹API_IDâ€‹Â â€‹=â€‹Â â€‹'7477141'â€‹Â â€‹#Â YOURÂ APIÂ IDÂ GETÂ FROMÂ my.telegram.org 
 â€‹CHAT_IDâ€‹Â â€‹=â€‹Â â€‹'-1001'â€‹#Â YOURÂ PRIVATEÂ GROUPÂ TOÂ VIEWÂ LOGSÂ ORÂ ERROR 
 â€‹USERNAMEâ€‹Â â€‹=â€‹Â â€‹'Rohithaditya'â€‹Â â€‹#Â YOURÂ USERNAMEÂ THISÂ ISÂ MANDTORY 
  
 â€‹###Â ABOVEÂ MAINÂ VARSÂ -------------------------------------------------------------------| 
 â€‹botâ€‹Â â€‹=â€‹Â â€‹telebotâ€‹.â€‹TeleBotâ€‹(â€‹tokenâ€‹=â€‹BOT_TOKENâ€‹) 
  
 â€‹@â€‹botâ€‹.â€‹message_handlerâ€‹(â€‹commandsâ€‹=â€‹[â€‹'showIds'â€‹]) 
 â€‹defâ€‹Â â€‹showIdsâ€‹(â€‹messageâ€‹): 
 â€‹Â Â Â Â â€‹tryâ€‹: 
 â€‹Â Â Â Â Â Â Â Â â€‹ifâ€‹Â â€‹messageâ€‹.â€‹from_userâ€‹.â€‹usernameâ€‹Â â€‹inâ€‹Â [â€‹'Parvat_R'â€‹,Â â€‹'Rohithaditya'â€‹,Â â€‹USERNAMEâ€‹]: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹fileâ€‹Â â€‹=â€‹Â â€‹openâ€‹(â€‹'joined_groups.txt'â€‹,Â â€‹'rÂ 'â€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹botâ€‹.â€‹send_documentâ€‹(â€‹messageâ€‹.â€‹chatâ€‹.â€‹idâ€‹,Â â€‹fileâ€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹fileâ€‹.â€‹closeâ€‹() 
  
 â€‹Â Â Â Â â€‹exceptâ€‹Â â€‹Exceptionâ€‹Â â€‹asâ€‹Â â€‹errorâ€‹: 
 â€‹Â Â Â Â Â Â Â Â â€‹botâ€‹.â€‹send_messageâ€‹(â€‹CHAT_IDâ€‹,Â â€‹strâ€‹(â€‹errorâ€‹)) 
  
 â€‹@â€‹botâ€‹.â€‹message_handlerâ€‹(â€‹commandsâ€‹=â€‹[â€‹'stats'â€‹,Â â€‹'groups'â€‹]) 
 â€‹defâ€‹Â â€‹statsâ€‹(â€‹messageâ€‹): 
 â€‹Â Â Â Â â€‹tryâ€‹: 
 â€‹Â Â Â Â Â Â Â Â â€‹ifâ€‹Â â€‹messageâ€‹.â€‹from_userâ€‹.â€‹usernameâ€‹Â â€‹inâ€‹[â€‹'armiy_b'â€‹,â€‹'armiy_v'â€‹,Â â€‹USERNAMEâ€‹]: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹printâ€‹(â€‹'SendingÂ StatsÂ ToÂ Owner'â€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹withâ€‹Â â€‹openâ€‹(â€‹'joined_groups.txt'â€‹,Â â€‹'r'â€‹)Â â€‹asâ€‹Â â€‹fileâ€‹: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹group_idsâ€‹Â â€‹=â€‹Â [] 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹forâ€‹Â â€‹lineâ€‹Â â€‹inâ€‹Â â€‹fileâ€‹.â€‹readlinesâ€‹(): 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹forâ€‹Â â€‹group_idâ€‹Â â€‹inâ€‹Â â€‹lineâ€‹.â€‹splitâ€‹(â€‹'Â 'â€‹): 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹group_idsâ€‹.â€‹appendâ€‹(â€‹group_idâ€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹no_of_pollsâ€‹Â â€‹=â€‹Â â€‹lenâ€‹(â€‹group_idsâ€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹no_of_groupsâ€‹Â â€‹=â€‹Â â€‹lenâ€‹(â€‹listâ€‹(â€‹setâ€‹(â€‹group_idsâ€‹))) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹group_idsâ€‹.â€‹clearâ€‹() 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹botâ€‹.â€‹reply_toâ€‹(â€‹messageâ€‹,Â â€‹f'NumberÂ ofÂ pollsÂ Maded:Â â€‹{â€‹no_of_pollsâ€‹}â€‹\nâ€‹NoÂ ofÂ groupsÂ botÂ hasÂ beenÂ added:Â â€‹{â€‹no_of_groupsâ€‹}â€‹'â€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹fileâ€‹.â€‹closeâ€‹() 
 â€‹Â Â Â Â Â Â Â Â â€‹elseâ€‹: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹botâ€‹.â€‹reply_toâ€‹(â€‹messageâ€‹,Â â€‹f'SorryÂ â€‹{â€‹messageâ€‹.â€‹from_userâ€‹.â€‹usernameâ€‹}â€‹!Â YouÂ AreÂ NotÂ AllowedÂ ToÂ UseÂ ThisÂ Command,'â€‹) 
 â€‹Â Â Â Â â€‹exceptâ€‹Â â€‹Exceptionâ€‹Â â€‹asâ€‹Â â€‹errorâ€‹: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹botâ€‹.â€‹send_messageâ€‹(â€‹CHAT_IDâ€‹,Â â€‹f'HiÂ Devs!!â€‹\nâ€‹HandleÂ ThisÂ ErrorÂ ploxâ€‹\nâ€‹{â€‹errorâ€‹}â€‹'â€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹tryâ€‹: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹group_idsâ€‹.â€‹clearâ€‹() 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹exceptâ€‹: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹pass 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹botâ€‹.â€‹reply_toâ€‹(â€‹messageâ€‹,Â â€‹f'AnÂ errorÂ occurred!â€‹\nâ€‹Error:Â â€‹{â€‹errorâ€‹}â€‹'â€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹botâ€‹.â€‹send_messageâ€‹(â€‹CHAT_IDâ€‹,Â â€‹f'AnÂ errorÂ occurred!â€‹\nâ€‹Error:Â â€‹{â€‹errorâ€‹}â€‹'â€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹botâ€‹.â€‹send_documentâ€‹(â€‹CHAT_IDâ€‹,Â â€‹'{message}'â€‹) 
  
 â€‹@â€‹botâ€‹.â€‹message_handlerâ€‹(â€‹commandsâ€‹=â€‹[â€‹'botlogs'â€‹]) 
 â€‹defâ€‹Â â€‹ViewTheLogsFileâ€‹(â€‹messageâ€‹): 
 â€‹Â Â Â Â â€‹tryâ€‹: 
 â€‹Â Â Â Â Â Â Â Â â€‹ifâ€‹Â â€‹messageâ€‹.â€‹from_userâ€‹.â€‹usernameâ€‹Â â€‹inâ€‹Â [â€‹'armiy_v'â€‹,Â â€‹'armiy_v'â€‹,Â â€‹USERNAMEâ€‹]: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹printâ€‹(â€‹'OwnerÂ AskedÂ ForÂ TheÂ Logs!'â€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹fileâ€‹Â â€‹=â€‹Â â€‹openâ€‹(â€‹'POLL_LOGS.txt'â€‹,Â â€‹'r'â€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹botâ€‹.â€‹send_documentâ€‹(â€‹messageâ€‹.â€‹chatâ€‹.â€‹idâ€‹,Â â€‹fileâ€‹,Â â€‹timeoutâ€‹=â€‹60â€‹,Â â€‹disable_notificationâ€‹=â€‹Trueâ€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹fileâ€‹.â€‹closeâ€‹() 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹printâ€‹(â€‹'LogsÂ SentÂ ToÂ Owner'â€‹) 
 â€‹Â Â Â Â Â Â Â Â â€‹elseâ€‹: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹botâ€‹.â€‹reply_toâ€‹(â€‹messageâ€‹,Â â€‹f'SorryÂ â€‹{â€‹messageâ€‹.â€‹from_userâ€‹.â€‹usernameâ€‹}â€‹!Â YouÂ AreÂ NotÂ AllowedÂ ForÂ ThisÂ Command,'â€‹) 
 â€‹Â Â Â Â â€‹exceptâ€‹Â â€‹Exceptionâ€‹Â â€‹asâ€‹Â â€‹errorâ€‹: 
 â€‹Â Â Â Â Â Â Â Â â€‹botâ€‹.â€‹reply_toâ€‹(â€‹messageâ€‹,Â â€‹f'Error:Â â€‹{â€‹errorâ€‹}â€‹'â€‹) 
  
 â€‹defâ€‹Â â€‹pollerâ€‹(â€‹messageâ€‹): 
 â€‹Â Â Â Â â€‹MSGâ€‹Â â€‹=â€‹Â â€‹message 
 â€‹Â Â Â Â â€‹tryâ€‹: 
 â€‹Â Â Â Â Â Â Â Â â€‹####Â ANÂ IMPORTANTÂ PROCESSÂ TOÂ SAVEÂ ALLÂ THEÂ USESÂ INÂ THEÂ POLL_LOGS.txtÂ FILE 
 â€‹Â Â Â Â Â Â Â Â â€‹tryâ€‹: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹file1â€‹Â â€‹=â€‹Â â€‹openâ€‹(â€‹'joined_groups.txt'â€‹,Â â€‹'a'â€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹fileâ€‹Â â€‹=â€‹Â â€‹openâ€‹(â€‹'POLL_LOGS.txt'â€‹,Â â€‹'a'â€‹) 
 â€‹Â Â Â Â Â Â Â Â â€‹exceptâ€‹Â â€‹FileNotFoundErrorâ€‹Â â€‹asâ€‹Â â€‹fnfeâ€‹: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹fileâ€‹Â â€‹=â€‹Â â€‹openâ€‹(â€‹'POLL_LOGS.txt'â€‹,Â â€‹'x'â€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹fileâ€‹.â€‹closeâ€‹() 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹fileâ€‹Â â€‹=â€‹Â â€‹openâ€‹(â€‹'POLL_LOGS.txt'â€‹,Â â€‹'a'â€‹) 
 â€‹Â Â Â Â Â Â Â Â â€‹text_to_add_in_log_fileâ€‹Â â€‹=â€‹Â â€‹f'''<pollbotÂ commandÂ =Â log> 
 â€‹Username:Â â€‹{â€‹messageâ€‹.â€‹from_userâ€‹.â€‹usernameâ€‹} 
 â€‹UserÂ IdÂ :Â â€‹{â€‹messageâ€‹.â€‹from_userâ€‹.â€‹idâ€‹} 
 â€‹CommandÂ :Â â€‹{â€‹messageâ€‹.â€‹textâ€‹} 
 â€‹OWNERÂ :Â â€‹{â€‹USERNAMEâ€‹} 
 â€‹ChatÂ IdÂ :Â â€‹{â€‹messageâ€‹.â€‹chatâ€‹.â€‹idâ€‹} 
 â€‹ChatType:Â â€‹{â€‹messageâ€‹.â€‹chatâ€‹.â€‹typeâ€‹} 
 â€‹GroupUserName:Â â€‹{â€‹messageâ€‹.â€‹chatâ€‹.â€‹usernameâ€‹} 
 â€‹DateÂ Â Â Â :Â â€‹{â€‹datetimeâ€‹.â€‹datetimeâ€‹.â€‹nowâ€‹()â€‹} 
  
 â€‹<splitÂ info_endÂ =Â True>CommandÂ Over</split> 
  
 â€‹''' 
 â€‹Â Â Â Â Â Â Â Â â€‹file1â€‹.â€‹writeâ€‹(â€‹f'Â â€‹{â€‹messageâ€‹.â€‹chatâ€‹.â€‹idâ€‹}â€‹'â€‹) 
 â€‹Â Â Â Â Â Â Â Â â€‹file1â€‹.â€‹closeâ€‹() 
 â€‹Â Â Â Â Â Â Â Â â€‹fileâ€‹.â€‹writeâ€‹(â€‹text_to_add_in_log_fileâ€‹) 
 â€‹Â Â Â Â Â Â Â Â â€‹fileâ€‹.â€‹closeâ€‹() 
 â€‹Â Â Â Â Â Â Â Â â€‹###Â PROCESSÂ DONE! 
 â€‹Â Â Â Â Â Â Â Â â€‹#TheÂ completeÂ commandÂ isÂ cutÂ onÂ '|' 
 â€‹Â Â Â Â Â Â Â Â â€‹text_arrâ€‹Â â€‹=â€‹Â â€‹messageâ€‹.â€‹textâ€‹.â€‹splitâ€‹(â€‹'|'â€‹) 
  
 â€‹Â Â Â Â Â Â Â Â â€‹#TheÂ splittedÂ textÂ areÂ insertedÂ inÂ theÂ commandsÂ list 
 â€‹Â Â Â Â Â Â Â Â â€‹#AlwaysÂ theÂ firstÂ commandÂ orÂ commands[0]Â willÂ beÂ '/poll 
 â€‹Â Â Â Â Â Â Â Â â€‹commandsâ€‹Â â€‹=â€‹Â [] 
  
 â€‹Â Â Â Â Â Â Â Â â€‹#AddingÂ splittedÂ textÂ inÂ commands: 
 â€‹Â Â Â Â Â Â Â Â â€‹forâ€‹Â â€‹cmdâ€‹Â â€‹inâ€‹Â â€‹text_arrâ€‹: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹#ws_re_textÂ =Â whiteÂ spaceÂ removedÂ commandÂ text 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹ws_re_textâ€‹Â â€‹=â€‹Â â€‹cmdâ€‹.â€‹stripâ€‹() 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹commandsâ€‹.â€‹appendâ€‹(â€‹ws_re_textâ€‹) 
  
 â€‹Â Â Â Â Â Â Â Â â€‹#NowÂ theÂ creationsÂ ofÂ commandsÂ forÂ poll: 
 â€‹Â Â Â Â Â Â Â Â â€‹questionâ€‹Â Â Â Â Â â€‹=â€‹Â â€‹commandsâ€‹[â€‹1â€‹] 
 â€‹Â Â Â Â Â Â Â Â â€‹optionsâ€‹Â Â Â Â Â Â â€‹=â€‹Â [] 
 â€‹Â Â Â Â Â Â Â Â â€‹multi_answerâ€‹Â â€‹=â€‹Â â€‹False 
 â€‹Â Â Â Â Â Â Â Â â€‹open_periodâ€‹Â Â â€‹=â€‹Â â€‹None 
 â€‹Â Â Â Â Â Â Â Â â€‹explanationâ€‹Â Â â€‹=â€‹Â â€‹None 
 â€‹Â Â Â Â Â Â Â Â â€‹disable_notiâ€‹Â â€‹=â€‹Â â€‹False 
 â€‹Â Â Â Â Â Â Â Â â€‹delete_msgâ€‹Â Â Â â€‹=â€‹Â â€‹False 
  
 â€‹Â Â Â Â Â Â Â Â â€‹#AddingÂ theÂ options: 
 â€‹Â Â Â Â Â Â Â Â â€‹optâ€‹Â â€‹=â€‹Â â€‹commandsâ€‹[â€‹2â€‹].â€‹splitâ€‹(â€‹','â€‹) 
 â€‹Â Â Â Â Â Â Â Â â€‹forâ€‹Â â€‹opâ€‹Â â€‹inâ€‹Â â€‹optâ€‹: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹nopâ€‹Â â€‹=â€‹Â â€‹opâ€‹.â€‹replaceâ€‹(â€‹'<.>'â€‹,Â â€‹','â€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹optionsâ€‹.â€‹appendâ€‹(â€‹nopâ€‹.â€‹stripâ€‹()) 
  
 â€‹Â Â Â Â Â Â Â Â â€‹#NowÂ checkingÂ theÂ **kwargsÂ inÂ theÂ commandÂ line 
 â€‹Â Â Â Â Â Â Â Â â€‹ifâ€‹Â â€‹lenâ€‹(â€‹commandsâ€‹)Â â€‹>â€‹Â â€‹3â€‹: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹forâ€‹Â â€‹cmdâ€‹Â â€‹inâ€‹Â â€‹commandsâ€‹[â€‹3â€‹:]: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹main_cmdâ€‹Â â€‹=â€‹Â â€‹cmdâ€‹.â€‹stripâ€‹().â€‹splitâ€‹(â€‹'='â€‹) 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â  
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹ifâ€‹Â â€‹main_cmdâ€‹[â€‹0â€‹].â€‹stripâ€‹()Â â€‹inâ€‹Â [â€‹'ma'â€‹,Â â€‹'multi_answer'â€‹,Â â€‹'m_a'â€‹,Â â€‹'mul_ans'â€‹]: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹multi_answerâ€‹Â â€‹=â€‹Â â€‹main_cmdâ€‹[â€‹1â€‹].â€‹stripâ€‹() 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â  
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹ifâ€‹Â â€‹main_cmdâ€‹[â€‹0â€‹].â€‹stripâ€‹()Â â€‹inâ€‹Â [â€‹'op'â€‹,Â â€‹'open_period'â€‹,Â â€‹'o_p'â€‹,Â â€‹'ope_per'â€‹]: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹open_periodâ€‹Â â€‹=â€‹Â â€‹main_cmdâ€‹[â€‹1â€‹].â€‹stripâ€‹() 
  
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹ifâ€‹Â â€‹main_cmdâ€‹[â€‹0â€‹].â€‹stripâ€‹()Â â€‹inâ€‹Â [â€‹'ex'â€‹,Â â€‹'explanation'â€‹,Â â€‹'expl'â€‹,Â â€‹'e_x'â€‹]: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹explanationâ€‹Â â€‹=â€‹Â â€‹main_cmdâ€‹[â€‹1â€‹].â€‹stripâ€‹() 
  
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹ifâ€‹Â â€‹main_cmdâ€‹[â€‹0â€‹].â€‹stripâ€‹()Â â€‹inâ€‹Â [â€‹'dn'â€‹,Â â€‹'d_n'â€‹,Â â€‹'disable_notification'â€‹,Â â€‹'dis_not'â€‹]: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹disable_notiâ€‹Â â€‹=â€‹Â â€‹main_cmdâ€‹[â€‹1â€‹].â€‹stripâ€‹() 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â  
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹ifâ€‹Â â€‹main_cmdâ€‹[â€‹0â€‹].â€‹stripâ€‹()Â â€‹inâ€‹Â [â€‹'dm'â€‹,Â â€‹'d_m'â€‹,Â â€‹'delete_message'â€‹,Â â€‹'del_msg'â€‹]: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â â€‹delete_msgâ€‹Â â€‹=â€‹Â â€‹True 
 â€‹Â Â Â Â Â Â Â Â  
 â€‹Â Â Â Â Â Â Â Â â€‹ifâ€‹Â â€‹delete_msgâ€‹: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹botâ€‹.â€‹delete_messageâ€‹(â€‹messageâ€‹.â€‹chatâ€‹.â€‹idâ€‹,Â â€‹messageâ€‹.â€‹idâ€‹) 
 â€‹Â Â Â Â Â Â Â Â â€‹#TheÂ mainÂ function 
 â€‹Â Â Â Â Â Â Â Â â€‹returnâ€‹Â â€‹botâ€‹.â€‹send_pollâ€‹( 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹messageâ€‹.â€‹chatâ€‹.â€‹idâ€‹, 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹questionâ€‹, 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹optionsâ€‹, 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹allows_multiple_answersâ€‹=â€‹Â â€‹multi_answerâ€‹, 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹explanationâ€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹=â€‹Â â€‹explanationâ€‹Â , 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹open_periodâ€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹=â€‹Â â€‹open_periodâ€‹Â , 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹disable_notificationsâ€‹Â Â â€‹=â€‹Â â€‹disable_notiâ€‹) 
 â€‹Â Â Â Â  
 â€‹Â Â Â Â â€‹exceptâ€‹Â â€‹IndexErrorâ€‹: 
 â€‹Â Â Â Â Â Â Â Â â€‹returnâ€‹Â â€‹botâ€‹.â€‹reply_toâ€‹(â€‹messageâ€‹,Â â€‹f'''Lol!!!Â YouÂ HaveÂ EnteredÂ WrongÂ Cmds 
 â€‹TheÂ formatÂ ofÂ theÂ commandÂ shouldÂ be: 
  
 â€‹`/pollÂ |Â yourÂ questionÂ |Â option1,Â option2,Â moreÂ optionsÂ |Â **kwargs` 
  
 â€‹ButÂ WhatÂ YouÂ SentÂ MeÂ wasğŸ¤£ğŸ¤£ğŸ˜‚ğŸ˜‚ğŸ˜ 
  
 â€‹{â€‹messageâ€‹.â€‹textâ€‹} 
  
 â€‹WhichÂ isÂ invalid. 
 â€‹ForÂ moreÂ helpÂ use:Â /help 
 â€‹orÂ contactÂ usÂ at:Â @Assist_profssor_bot 
 â€‹'''â€‹) 
 â€‹Â Â Â Â â€‹exceptâ€‹Â â€‹Exceptionâ€‹Â â€‹asâ€‹Â â€‹errorâ€‹: 
 â€‹Â Â Â Â Â Â Â Â â€‹botâ€‹.â€‹send_messageâ€‹(â€‹CHAT_IDâ€‹,â€‹f'''ErrorÂ FromÂ PollÂ Bot! 
  
 â€‹ErrorÂ Â ::Â â€‹{â€‹errorâ€‹} 
  
 â€‹-------------------------------- 
  
 â€‹Command::Â â€‹{â€‹messageâ€‹.â€‹textâ€‹} 
  
 â€‹-------------------------------- 
  
 â€‹UserDetails:Â â€‹{â€‹messageâ€‹.â€‹from_userâ€‹} 
  
 â€‹-------------------------------- 
  
 â€‹DateÂ Â Â ::Â â€‹{â€‹messageâ€‹.â€‹dateâ€‹} 
  
 â€‹-------------------------------- 
  
 â€‹TheÂ CompleteÂ Detail: 
 â€‹{â€‹messageâ€‹} 
  
  
 â€‹'''â€‹) 
 â€‹Â Â Â Â Â Â Â Â  
 â€‹Â Â Â Â Â Â Â Â â€‹returnâ€‹Â â€‹botâ€‹.â€‹reply_toâ€‹(â€‹messageâ€‹,Â â€‹f'''AnÂ UnexpectedÂ ErrorÂ Occured! 
 â€‹Error::Â Â â€‹{â€‹errorâ€‹} 
 â€‹TheÂ errorÂ wasÂ informedÂ toÂ @venilabots'''â€‹) 
 â€‹Â Â Â Â Â Â Â Â  
 â€‹Â Â Â Â Â Â Â Â  
  
 â€‹@â€‹botâ€‹.â€‹message_handlerâ€‹(â€‹commandsâ€‹=â€‹[â€‹'poll'â€‹]) 
 â€‹defâ€‹Â â€‹pollNowâ€‹(â€‹messageâ€‹): 
 â€‹Â Â Â Â â€‹pollerâ€‹(â€‹messageâ€‹) 
  
 â€‹@â€‹botâ€‹.â€‹message_handlerâ€‹(â€‹commandsâ€‹=â€‹[â€‹'help'â€‹]) 
 â€‹defâ€‹Â â€‹helperâ€‹(â€‹messageâ€‹): 
 â€‹Â Â Â Â â€‹returnâ€‹Â â€‹botâ€‹.â€‹reply_toâ€‹(â€‹messageâ€‹,Â â€‹f'''MyÂ NameÂ DefinesÂ WhoÂ AmÂ I.Â  
 â€‹Â Â Â Â WhatÂ CanÂ IÂ Do? 
 â€‹Â Â Â Â 1.Â CreateÂ polls 
 â€‹Â Â Â Â 2.Â UnlimitedÂ Polls 
 â€‹Â Â Â Â 3.Â VastÂ options 
  
 â€‹Â MainÂ Commands: 
 â€‹Â Â Â Â /help 
 â€‹Â Â Â Â /alive 
 â€‹Â Â Â Â /poll 
  
 â€‹Functions: 
 â€‹/help: 
 â€‹Â Â Â Â SeeÂ theÂ HelpÂ Text 
  
 â€‹/alive: 
 â€‹Â Â Â Â CheckÂ ifÂ theÂ botÂ isÂ runningÂ orÂ not 
  
 â€‹/poll: 
 â€‹Â Â Â Â CreateÂ polls. 
  
 â€‹HowÂ ToÂ CreateÂ Polls: 
  
 â€‹use: 
 â€‹/pollÂ |Â YourÂ QuestionÂ |Â Option1,Â Option2,Â Option3,Â more_optionÂ |Â **kwargs 
 â€‹YouÂ canÂ addÂ AsÂ mayÂ optionsÂ asÂ youÂ want.Â (minimum-1) 
  
 â€‹whatÂ isÂ **kwargs? 
 â€‹**kwargsÂ areÂ theÂ optionalÂ commands,Â thatÂ youÂ canÂ passÂ whenÂ necessary! 
 â€‹thoseÂ are: 
 â€‹Â Â Â Â multi_answerÂ =Â True/False 
 â€‹Â Â Â Â Â Â Â Â ThisÂ enablesÂ orÂ disablesÂ TheÂ multipleÂ answerÂ mode.Â ByÂ defaultÂ ItÂ isÂ False. 
 â€‹Â Â Â Â Â Â Â Â example: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â /pollÂ |Â ThisÂ isÂ myÂ questionÂ |Â Ans1,Â Ans2Â |Â multi_answerÂ =Â True 
  
 â€‹Â Â Â Â opÂ =Â seconds 
 â€‹Â Â Â Â Â Â Â Â ThisÂ tellsÂ howÂ manyÂ secondsÂ willÂ theÂ pollÂ willÂ last. 
 â€‹Â Â Â Â Â Â Â Â ItÂ mightÂ beÂ 'op'Â orÂ 'open_period' 
 â€‹Â Â Â Â Â Â Â Â example: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â /pollÂ |Â ThisÂ isÂ myÂ questionÂ |Â Ans1,Â Ans2Â |Â opÂ =Â 60 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â NowÂ theÂ pollÂ willÂ lastÂ forÂ 60Â seconds. 
  
 â€‹Â Â Â Â dnÂ =Â True/False 
 â€‹Â Â Â Â Â Â Â Â ThisÂ tellsÂ thatÂ theÂ pollÂ shouldÂ beÂ notifiedÂ inÂ theÂ notificationsÂ ofÂ the 
 â€‹Â Â Â Â Â Â Â Â groupÂ members.Â ByÂ DefaultÂ itÂ isÂ True.Â ItÂ mightÂ beÂ 'dn'Â orÂ 'disable_notification'. 
 â€‹Â Â Â Â Â Â Â Â example: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â /pollÂ |Â ThisÂ isÂ myÂ questionÂ |Â Ans1,Â Ans2Â |Â dnÂ =Â False 
  
 â€‹DidÂ youÂ know,Â youÂ canÂ useÂ multipleÂ optionalÂ commandsÂ orÂ dontÂ useÂ it: 
 â€‹Example: 
 â€‹Â Â Â Â 1. 
 â€‹Â Â Â Â Â Â Â Â /pollÂ |Â HiÂ thereÂ |Â Hello,Â GoodÂ bye 
  
 â€‹Â Â Â Â 2. 
 â€‹Â Â Â Â Â Â Â Â /pollÂ |Â ThisÂ willÂ closeÂ inÂ 10sÂ |Â Nice,Â BadÂ |Â opÂ =Â 10 
 â€‹Â Â Â Â Â Â Â Â  
 â€‹Â Â Â Â 3. 
 â€‹Â Â Â Â Â Â Â Â /pollÂ |Â HelloÂ |Â Hi,Â Bye,Â HiÂ dev,Â ByeÂ humanÂ |Â maÂ =Â TrueÂ |Â open_periodÂ =Â 50 
  
 â€‹Note: 
 â€‹Â Â Â Â -UseÂ ','Â toÂ splitÂ theÂ options. 
 â€‹Â Â Â Â -EveryÂ partÂ isÂ splitÂ byÂ '|'. 
 â€‹Â Â Â Â -ToÂ useÂ ','Â inÂ optionÂ use:Â '<.>' 
  
 â€‹
  
 â€‹Devs: 
@arimiy_v
  
 â€‹CreatedÂ with: 
 â€‹python, 
 â€‹pyTelegramBotAPI 
 â€‹'''â€‹) 
  
  
 â€‹@â€‹botâ€‹.â€‹message_handlerâ€‹(â€‹commandsâ€‹=â€‹[â€‹'alive'â€‹]) 
 â€‹defâ€‹Â â€‹aliveâ€‹(â€‹messageâ€‹): 
 â€‹Â Â Â Â â€‹botâ€‹.â€‹reply_toâ€‹(â€‹messageâ€‹,Â â€‹f'HeyÂ â€‹{â€‹messageâ€‹.â€‹from_userâ€‹.â€‹usernameâ€‹}â€‹,Â ReadyÂ ToÂ ServeÂ You'â€‹) 
  
 â€‹'''err_countÂ =Â 0Â #CheckÂ forÂ errors 
 â€‹whileÂ True: 
 â€‹Â Â Â Â try: 
 â€‹Â Â Â Â Â Â Â Â bot.polling() 
 â€‹Â Â Â Â exceptÂ FileNotFoundErrorÂ asÂ e: 
 â€‹Â Â Â Â Â Â Â Â print(e) 
 â€‹Â Â Â Â Â Â Â Â err_countÂ +=1 
 â€‹Â Â Â Â Â Â Â Â print(f'ErrorÂ Number:Â {err_count}') 
 â€‹Â Â Â Â Â Â Â Â ifÂ err_countÂ ==Â 10: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â break 
 â€‹''' 
 â€‹@â€‹botâ€‹.â€‹message_handlerâ€‹(â€‹commandsâ€‹=â€‹[â€‹'start'â€‹]) 
 â€‹defâ€‹Â â€‹aliveâ€‹(â€‹messageâ€‹): 
 â€‹Â Â Â Â â€‹botâ€‹.â€‹reply_toâ€‹(â€‹messageâ€‹,Â â€‹f'HeyaÂ â€‹{â€‹messageâ€‹.â€‹from_userâ€‹.â€‹usernameâ€‹}â€‹,Â IÂ amÂ thereÂ toÂ helpÂ youÂ inÂ polls.Â ButÂ thisÂ cmdÂ isÂ bitÂ oldÂ tryÂ /help.Â SEEÂ @Assist_profssor_botÂ FORÂ MOREÂ BOTSÂ LIKEÂ THIS'â€‹) 
  
 â€‹err_countâ€‹Â â€‹=â€‹Â â€‹0â€‹Â â€‹#CheckÂ forÂ errors 
 â€‹whileâ€‹Â â€‹Trueâ€‹: 
 â€‹Â Â Â Â â€‹tryâ€‹: 
 â€‹Â Â Â Â Â Â Â Â â€‹botâ€‹.â€‹pollingâ€‹() 
 â€‹Â Â Â Â â€‹exceptâ€‹Â â€‹FileNotFoundErrorâ€‹Â â€‹asâ€‹Â â€‹eâ€‹: 
 â€‹Â Â Â Â Â Â Â Â â€‹printâ€‹(â€‹eâ€‹) 
 â€‹Â Â Â Â Â Â Â Â â€‹err_countâ€‹Â â€‹+=â€‹1 
 â€‹Â Â Â Â Â Â Â Â â€‹printâ€‹(â€‹f'ErrorÂ Number:Â â€‹{â€‹err_countâ€‹}â€‹'â€‹) 
 â€‹Â Â Â Â Â Â Â Â â€‹ifâ€‹Â â€‹err_countâ€‹Â â€‹==â€‹Â â€‹10â€‹: 
 â€‹Â Â Â Â Â Â Â Â Â Â Â Â â€‹break 
 â€‹""" 
 â€‹PLEASEÂ KEEPÂ CREDITS 
 â€‹"""
